version: "3"
services:
  # mysql
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'blog'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3366:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - db_data:/var/lib/mysql
    # Make sure log colors show up correctly
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "1"
volumes:
  db_data:
